version: "3"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: oshomework
    ports:
      - 3306:3306
    expose:
      - "3306"

  oshomework:
    build: .
    depends_on:
      - mysql
    environment: 
      MYSQLURL: 172.18.0.1
      MYSQLPORT: 3306
      MYSQLUSERNAME: root
      MYSQLPASSWORD: oshomework
      MYSQLDATABASE: oshomework
    ports:
      - 8080:8080
    expose:
      - "8080"
volumes:
    dbdata:
